services:
  ciop:
    build:
      context: .
      dockerfile: Dockerfile

    image: ciop-central:0.1.0
    container_name: ciop_web

    ports:
      - "8080:80"

    environment:
      CIOP_DATA_DIR: /data
      CIOP_REFRESH_SEC: "20"

    volumes:
      - ../CIOP_DATA:/data:ro
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src

    restart: unless-stopped